(function(){
'use strict';
const STORE='musicPhi:quants:v1',SETTINGS='musicPhi:settings:v1',CONTEXT='phiContext:events:v1';
const NOTES=[
 {n:'C',m:60,k:'A'},{n:'D',m:62,k:'S'},{n:'E',m:64,k:'D'},{n:'F',m:65,k:'F'},{n:'G',m:67,k:'G'},
 {n:'A',m:69,k:'H'},{n:'B',m:71,k:'J'},{n:'C',m:72,k:'K'},{n:'D',m:74,k:'L'},{n:'E',m:76,k:';'}
];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
let settings=read(SETTINGS,{instrument:'grand',clef:'treble',meter:'4/4',bpm:90,dynamic:'mf',transpose:0});
let current=[],pressed=new Map(),ctx=null,master=null,compressor=null,quants=read(STORE,[]);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function install(){
 const host=document.createElement('section');host.className='music-quant-lab';host.innerHTML=`
 <div class="mq-head"><div><small>PLAY OVER INFINITY RADIO</small><h2>Music Quant Piano</h2></div><strong id="mqBalance">0 Music Quants</strong></div>
 <p class="mq-intro">Five recorded notes form one Music Quant. Note pitch, hold time, spacing, instrument, clef, meter, tempo and dynamics stay editable.</p>
 <div class="mq-controls">
  <label>Instrument<select id="mqInstrument"><option value="grand">Grand piano</option><option value="electric">Electric piano</option><option value="organ">Organ</option><option value="bell">Bell</option></select></label>
  <label>Clef<select id="mqClef"><option value="treble">Treble</option><option value="bass">Bass</option></select></label>
  <label>Meter<select id="mqMeter"><option>4/4</option><option>3/4</option><option>6/8</option><option>2/4</option></select></label>
  <label>Tempo<input id="mqBpm" type="number" min="30" max="240" step="1"></label>
  <label>Dynamics<select id="mqDynamic"><option>pp</option><option>p</option><option>mp</option><option>mf</option><option>f</option><option>ff</option></select></label>
  <label>Pitch<select id="mqTranspose"><option value="-12">−1 octave</option><option value="0">Concert</option><option value="12">+1 octave</option></select></label>
 </div>
 <div class="mq-staff" id="mqLiveStaff"></div><div class="mq-progress"><span id="mqProgress">0/5 notes</span><button id="mqClear" type="button">Clear</button></div>
 <div class="mq-keys" id="mqKeys"></div>
 <div class="mq-list-head"><h3>Recorded Music Quants</h3><small>Stored on this device with a provenance hash</small></div><div id="mqList"></div>`;
 const style=document.createElement('style');style.textContent=`
 .music-quant-lab{margin-top:14px;padding:14px;border:1px solid #38677a;border-radius:16px;background:linear-gradient(160deg,#081827,#040b13);color:#eaffff}.mq-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.mq-head small{font-size:9px;letter-spacing:.15em;color:#78c9d1}.mq-head h2{margin:3px 0;font-size:22px}.mq-head strong{color:#ffe15a;font-size:12px}.mq-intro{color:#a7c0c9;font-size:12px}.mq-controls{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mq-controls label{font-size:9px;letter-spacing:.08em;color:#8fc2ca}.mq-controls select,.mq-controls input{display:block;width:100%;margin-top:4px;padding:8px;border:1px solid #315d75;border-radius:9px;background:#020812;color:#fff}.mq-staff{margin:14px 0 8px;border-radius:12px;background:#fff;overflow:hidden;min-height:126px}.mq-staff svg{display:block;width:100%;height:126px}.mq-progress{display:flex;justify-content:space-between;align-items:center;font-weight:800}.mq-progress button{border:1px solid #315d75;border-radius:8px;background:#071426;color:#cff;padding:7px 10px}.mq-keys{display:grid;grid-template-columns:repeat(10,1fr);gap:3px;margin:10px 0 18px;-webkit-user-select:none;user-select:none;-webkit-touch-callout:none}.mq-key,.mq-key *{-webkit-user-select:none!important;user-select:none!important;-webkit-touch-callout:none!important}.mq-key{min-width:0;height:88px;border:1px solid #789;border-radius:0 0 8px 8px;background:#fff;color:#071426;font-weight:900;touch-action:none}.mq-key.active{background:#ffe15a;transform:translateY(2px)}.mq-key small{display:block;font-size:8px;color:#657}.mq-list-head{display:flex;align-items:end;justify-content:space-between;gap:10px;border-top:1px solid #ffffff17;padding-top:12px}.mq-list-head h3{margin:0}.mq-list-head small{color:#7899a5}.mq-card{margin-top:10px;border:1px solid #25495b;border-radius:12px;padding:10px;background:#06111d}.mq-card-head{display:flex;justify-content:space-between;gap:8px}.mq-card code{font-size:9px;color:#7fcbd0}.mq-note-edit{display:grid;grid-template-columns:repeat(5,1fr);gap:5px}.mq-note-edit label{font-size:9px}.mq-note-edit input{width:100%;padding:6px;background:#020812;border:1px solid #315d75;border-radius:7px;color:#fff}.mq-mini-staff{background:#fff;border-radius:8px;margin:8px 0}.mq-mini-staff svg{display:block;width:100%;height:94px}.mq-context{margin-top:8px;padding:7px 8px;border-radius:8px;background:#0c2230;color:#aee;font-size:10px}@media(max-width:560px){.mq-controls{grid-template-columns:repeat(2,1fr)}.mq-keys{gap:2px}.mq-key{height:74px;font-size:11px}}`;document.head.appendChild(style);
 document.querySelector('.radio-shell')?.appendChild(host);bind();renderKeys();renderAll();
}
function bind(){
 const ids={instrument:'mqInstrument',clef:'mqClef',meter:'mqMeter',bpm:'mqBpm',dynamic:'mqDynamic',transpose:'mqTranspose'};
 Object.entries(ids).forEach(([key,id])=>{const el=document.getElementById(id);el.value=settings[key];el.onchange=()=>{settings[key]=key==='bpm'||key==='transpose'?Number(el.value):el.value;write(SETTINGS,settings);renderLive()}});
 document.getElementById('mqClear').onclick=()=>{current=[];renderLive()};
 addEventListener('keydown',e=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test(document.activeElement?.tagName))return;const i=NOTES.findIndex(x=>x.k.toLowerCase()===e.key.toLowerCase());if(i>=0){e.preventDefault();down(i)}});
 addEventListener('keyup',e=>{const i=NOTES.findIndex(x=>x.k.toLowerCase()===e.key.toLowerCase());if(i>=0)up(i)});
}
function renderKeys(){const el=document.getElementById('mqKeys');el.innerHTML=NOTES.map((x,i)=>'<button class="mq-key" type="button" data-i="'+i+'">'+x.n+'<small>'+x.k+'</small></button>').join('');['contextmenu','selectstart','dragstart'].forEach(type=>el.addEventListener(type,e=>e.preventDefault()));el.querySelectorAll('.mq-key').forEach(b=>{const i=Number(b.dataset.i);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);down(i)};b.onpointerup=()=>up(i);b.onpointercancel=()=>up(i)})}
function ensureAudio(){if(!ctx){ctx=new (AudioContext||webkitAudioContext)();master=ctx.createGain();master.gain.value=.48;compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-16;compressor.knee.value=12;compressor.ratio.value=3;compressor.attack.value=.003;compressor.release.value=.25;master.connect(compressor);compressor.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume()}
function wave(){return settings.instrument==='organ'?'square':settings.instrument==='electric'?'triangle':settings.instrument==='bell'?'sine':'triangle'}
function down(i){if(pressed.has(i)||current.length>=5)return;ensureAudio();const midi=NOTES[i].m+Number(settings.transpose||0),freq=440*Math.pow(2,(midi-69)/12),gain=ctx.createGain(),now=ctx.currentTime,level=settings.dynamic==='ff'?.34:settings.dynamic==='f'?.28:settings.dynamic==='pp'?.09:.22;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(level,now+.012);gain.gain.exponentialRampToValueAtTime(Math.max(.025,level*.32),now+1.35);gain.connect(master);const partials=[{ratio:1,type:wave(),amount:1},{ratio:2,type:'sine',amount:.24},{ratio:3,type:'sine',amount:.09}];const oscillators=partials.map(partial=>{const osc=ctx.createOscillator(),partialGain=ctx.createGain();osc.type=partial.type;osc.frequency.value=freq*partial.ratio;partialGain.gain.value=partial.amount;osc.connect(partialGain);partialGain.connect(gain);osc.start(now);return osc}),entry={at:performance.now(),startedAt:Date.now(),oscillators,gain,midi,index:i,timer:0};entry.timer=setTimeout(()=>up(i),1200);pressed.set(i,entry);document.querySelector('.mq-key[data-i="'+i+'"]')?.classList.add('active')}
function up(i){const p=pressed.get(i);if(!p)return;pressed.delete(i);clearTimeout(p.timer);const hold=Math.max(60,Math.round(performance.now()-p.at)),now=ctx.currentTime;p.gain.gain.cancelScheduledValues(now);p.gain.gain.setValueAtTime(Math.max(.0001,p.gain.gain.value),now);p.gain.gain.exponentialRampToValueAtTime(.0001,now+.32);p.oscillators.forEach(osc=>osc.stop(now+.35));document.querySelector('.mq-key[data-i="'+i+'"]')?.classList.remove('active');const previous=current[current.length-1],offset=previous?Math.max(0,p.startedAt-previous.startedAt):0;current.push({name:NOTES[i].n,midi:p.midi,holdMs:hold,offsetMs:offset});renderLive();if(current.length===5)void mint()}
async function digest(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function captureContext(){const now=Date.now(),events=read(CONTEXT,[]).filter(e=>now-Date.parse(e?.at||0)<60*60*1000).slice(0,12).map(e=>({action:String(e.action||'').slice(0,40),topic:String(e.topic||'').slice(0,180),channel:String(e.channel||'').slice(0,100),program:String(e.program||'').slice(0,180),page:String(e.page||'').slice(0,180),at:String(e.at||'')}));const song=String(document.getElementById('np-channel')?.textContent||'').trim().slice(0,180);return {version:1,playback:{song,station:'Infinity Radio',playing:document.getElementById('play-btn')?.textContent==='⏸',capturedAt:new Date().toISOString()},events,retention:'user-owned-context'};}
async function mint(){const body={version:2,context:captureContext(),notes:current.map(x=>({...x})),settings:{...settings},createdAt:new Date().toISOString(),source:'infinity-radio-music-quant'};body.hash=await digest(body);body.id='mq_'+body.hash.slice(0,20);quants=[body,...read(STORE,[]).filter(q=>q.id!==body.id)].slice(0,500);if(!write(STORE,quants)){document.getElementById('mqProgress').textContent='Save failed — browser storage unavailable';return}window.dispatchEvent(new CustomEvent('musicquant:changed',{detail:{action:'mint',quantId:body.id}}));window.dispatchEvent(new CustomEvent('controlphi:wallet-change',{detail:{musicQuants:quants.length,source:'music-quant-piano'}}));window.ControlPhi?.refreshWallet?.();current=[];renderAll();document.getElementById('mqProgress').textContent='Saved Music Quant '+quants.length}
function staff(notes,clef,height=126){const ys=[34,46,58,70,82],base=clef==='bass'?48:60;let s='<svg viewBox="0 0 600 '+height+'" role="img" aria-label="Music staff">';ys.forEach(y=>s+='<line x1="48" y1="'+y+'" x2="580" y2="'+y+'" stroke="#27333a" stroke-width="1"/>');s+='<text x="10" y="72" fill="#101820" font-size="42">'+(clef==='bass'?'𝄢':'𝄞')+'</text>';notes.forEach((n,i)=>{const x=105+i*92,y=82-(n.midi-base)*3;s+='<ellipse cx="'+x+'" cy="'+Math.max(16,Math.min(104,y))+'" rx="9" ry="7" transform="rotate(-18 '+x+' '+y+')" fill="#111"/><line x1="'+(x+7)+'" y1="'+y+'" x2="'+(x+7)+'" y2="'+(y-32)+'" stroke="#111" stroke-width="2"/><text x="'+(x-22)+'" y="116" fill="#35434b" font-size="10">'+esc(n.name)+' · '+n.holdMs+'ms</text>'});return s+'</svg>'}
function renderLive(){document.getElementById('mqLiveStaff').innerHTML=staff(current,settings.clef);document.getElementById('mqProgress').textContent=current.length+'/5 notes'}
function renderAll(){renderLive();document.getElementById('mqBalance').textContent=quants.length+' Music Quant'+(quants.length===1?'':'s');const list=document.getElementById('mqList');list.innerHTML=quants.map((q,qi)=>'<article class="mq-card" id="'+esc(q.id)+'" data-qi="'+qi+'"><div class="mq-card-head"><strong>Music Quant '+(quants.length-qi)+'</strong><code>'+esc(q.hash.slice(0,16))+'</code></div><div class="mq-mini-staff">'+staff(q.notes,q.settings.clef,94)+'</div><div class="mq-note-edit">'+q.notes.map((n,ni)=>'<label>'+esc(n.name)+' hold<input type="number" min="40" max="16000" step="10" value="'+n.holdMs+'" data-ni="'+ni+'"></label>').join('')+'</div><small>'+esc(q.settings.instrument)+' · '+esc(q.settings.clef)+' · '+esc(q.settings.meter)+' · '+q.settings.bpm+' BPM · '+esc(q.settings.dynamic)+'</small>'+(q.context?.playback?.song?'<div class="mq-context"><b>Context</b> · '+esc(q.context.playback.song)+(q.context.events?.length?' · '+q.context.events.length+' purposeful event'+(q.context.events.length===1?'':'s'):'')+'</div>':'')+'</article>').join('')||'<p class="mq-intro">Play and release five keys to record the first Music Quant.</p>';list.querySelectorAll('.mq-card input').forEach(input=>input.onchange=async()=>{const card=input.closest('.mq-card'),q=quants[Number(card.dataset.qi)],n=q.notes[Number(input.dataset.ni)];n.holdMs=Math.max(40,Math.min(16000,Number(input.value)||n.holdMs));const clone={...q};delete clone.hash;delete clone.id;q.hash=await digest(clone);q.id='mq_'+q.hash.slice(0,20);write(STORE,quants);window.dispatchEvent(new CustomEvent('musicquant:changed',{detail:{action:'edit',quantId:q.id}}));renderAll()})}
addEventListener('musicquant:cloud-synced',()=>{quants=read(STORE,[]);renderAll()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
